Update mock-mount-s3 to require '--max-throughput-gbps' argument
awslabs/mountpoint-s3 pull request #1018
Opened 2024-09-17 09:17 UTC by dannycjones

## Description of change

It was unclear to me when first using `mock-mount-s3` that it will limit throughput based on the value for `--max-throughput-gbps`, and that this will default to 10Gbps as real Mountpoint does if it can't detect the correct value.

This change requires the argument to be specified, so that the user can be forced to acknowledge this default or choose a better value for the use case.

Relevant issues: N/A

## Does this change impact existing behavior?

It does, but only for the mock binary. You now must specify `--max-throughput-gbps <Gbps>`.

## Does this change need a changelog entry in any of the crates?

No.

---

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license and I agree to the terms of the [Developer Certificate of Origin (DCO)](https://developercertificate.org/).

2024-09-23 15:33 UTC, monthonk requested changes
Does this binary really compile? I have to add `features = ["thread-pool"]` for the futures crate to make it work. Maybe we should also fix that.

2024-09-23 15:33 UTC, monthonk commented on mountpoint-s3/src/bin/mock-mount-s3.rs
> +            "must set --max-throughput-gbps when using mock-mount-s3 binary"
This doesn't match the real argument.
```suggestion
            "must set --maximum-throughput-gbps when using mock-mount-s3 binary"
```

2024-09-24 09:06 UTC, dannycjones commented
>Does this binary really compile? I have to add features = ["thread-pool"] for the futures crate to make it work. Maybe we should also fix that.

Yeah, I wasn't sure on the best practice here. I'll submit a possible fix in another PR, I think it will be an improvement.

2024-09-24 09:39 UTC, monthonk approved these changes
Sounds good! thanks Danny.

2024-09-24 09:52 UTC, merged