Create seq_write_small.fio
awslabs/mountpoint-s3 pull request #1190
Opened 2024-12-09 09:56 UTC by renanmagagnin

Added a new benchmark for writing of small files.

### Does this change impact existing behavior? No

### Does this change need a changelog entry? No

---

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license and I agree to the terms of the [Developer Certificate of Origin (DCO)](https://developercertificate.org/).

2024-12-09 10:14 UTC, muddyfish commented on mountpoint-s3/scripts/fio/write/seq_write_small.fio
> +size=5m
We should have a quick discussion on if 5MB is the right size for this

2024-12-10 14:31 UTC, muddyfish reviewed
~~Can you include what results format we get as a comment?~~

Nevermind, I see we're running a benchmark action which should include it

2024-12-10 15:46 UTC, monthonk commented on mountpoint-s3/scripts/fio/write_latency/seq_write_small.fio
> +[sequential_write_small_file]
It's not really clear from the name what number we want to measure here. Could we have better naming for it?

2024-12-10 15:46 UTC, monthonk commented on mountpoint-s3/scripts/fs_latency_bench.sh
> +run_start_time_to_first_byte_benchmarks() {
We probably should change this function name too. It's not time to first byte for the write benchmark.

2024-12-10 16:19 UTC, monthonk requested changes

2024-12-10 16:19 UTC, monthonk commented on mountpoint-s3/scripts/fs_latency_bench.sh
>    job_name=$(basename "${job_file}")
We should update indentation for this block. Sorry, I missed this part in the last review.

2024-12-11 10:10 UTC, merged