Add support for --request-payer requester cli flag - Fixes #148
awslabs/mountpoint-s3 pull request #168
Opened 2023-03-19 00:22 UTC by arjvik

---

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license and I agree to the terms of the [Developer Certificate of Origin (DCO)](https://developercertificate.org/).

2023-03-19 23:35 UTC, arjvik commented
Linking to #148, since apparently titles don't get the same treatment as comments

2023-03-20 10:51 UTC, dannycjones requested changes
Hey, thanks for your contribution!

Added some minor style comments.

2023-03-20 10:51 UTC, dannycjones commented on mountpoint-s3-client/src/s3_crt_client.rs
>          })
Prefer to inline this, and also to maintain trailing comma.

```suggestion
        Ok(Self {
            allocator,
            s3_client,
            event_loop_group,
            endpoint,
            next_request_counter: AtomicU64::new(0),
            user_agent_header,
            request_payer: config.request_payer,
        })
```

2023-03-20 10:51 UTC, dannycjones commented on mountpoint-s3-client/src/s3_crt_client.rs
> +        }
We can make this a bit simpler as we don't care about the `None` case. [Reported by clippy check](https://github.com/awslabs/mountpoint-s3/actions/runs/4458017462/jobs/7846616113#step:6:83).

```suggestion
        if let Some(ref payer) = self.request_payer {
            message.add_header(&Header::new("x-amz-request-payer", payer))?;
        }
```

2023-03-20 10:55 UTC, dannycjones commented on mountpoint-s3/src/main.rs
> +        request_payer: args.request_payer
Also add trailing comma here.

```suggestion
        request_payer: args.request_payer,
```

2023-03-20 11:05 UTC, arjvik commented
Thanks for the style comments @dannycjones - I committed all of the changes you suggested!

2023-03-20 14:03 UTC, monthonk requested changes
Thanks for taking a look at this feature!

Added some comments about the CLI argument.

2023-03-20 16:44 UTC, dannycjones reviewed
Seconding @monthonk's comments, otherwise LGTM.

2023-03-24 09:16 UTC, arjvik commented
Otherwise, this should be ready to merge? @monthonk @dannycjones

2023-03-24 10:03 UTC, monthonk reviewed
Almost there. We need to rebase to resolve the conflict with current main branch and it should be ready.

2023-03-24 10:03 UTC, monthonk commented on mountpoint-s3/src/main.rs
> +    #[clap(long, help = "Value of the 'x-amz-request-payer' header sent to S3")]
Update help text a bit, should be something like "Enable accessing to requester pays bucket".

2023-03-24 16:49 UTC, arjvik commented
Rebase complete! @monthonk

2023-03-24 17:28 UTC, monthonk approved these changes
LGTM!

2023-03-24 18:04 UTC, dannycjones approved these changes

2023-03-24 18:04 UTC, merged

2023-03-24 18:04 UTC, dannycjones commented
Merged - thanks for the contribution!