Docker inclusion for mountpoint S3
awslabs/mountpoint-s3 pull request #173
Opened 2023-03-21 15:53 UTC by mheshwg

Mountpoint for Amazon S3 is dockerised with instruction to run the same.

---

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license and I agree to the terms of the [Developer Certificate of Origin (DCO)](https://developercertificate.org/).

2023-03-23 14:02 UTC, monthonk requested changes
Thanks for trying it out on Docker and contributing to the project! I have a few comments on what we should consider.

2023-03-23 14:23 UTC, dannycjones commented on Dockerfile
> +FROM amazonlinux:latest
If you do continue to use Amazon Linux, please also use a stable major version tag from the AWS ECR repository such as `public.ecr.aws/amazonlinux/amazonlinux:2023`. (more info on the ECR image: https://gallery.ecr.aws/amazonlinux/amazonlinux)

2023-03-23 15:05 UTC, mheshwg commented on Dockerfile
> +#CONTENT
Removed the copyright text

2023-03-23 15:07 UTC, mheshwg commented on Dockerfile
> +FROM amazonlinux:latest
Included base image amazonlinux:2023 stable version.

2023-03-23 15:39 UTC, mheshwg commented on Dockerfile
Created a directory docker to hold Dockerfile. good one thank you.

2023-03-23 15:40 UTC, mheshwg commented on README.md
> +    docker build mount-s3 .
Fixed it. missing the `-t`

2023-03-23 15:40 UTC, mheshwg commented on README.md
> +     docker run -it --cap-add SYS_ADMIN --device /dev/fuse --env AWS_ACCESS_KEY_ID=<<KEY ID>> --env AWS_SECRET_ACCESS_KEY=<<Secret>> --env AWS_DEFAULT_REGION=<<AWS Region>> mount_s3 /bin/bash -c "./m
Good one. fixed it.

2023-03-23 15:41 UTC, mheshwg commented on README.md
> +     docker run -it --cap-add SYS_ADMIN --device /dev/fuse --env AWS_ACCESS_KEY_ID=<<KEY ID>> --env AWS_SECRET_ACCESS_KEY=<<Secret>> --env AWS_DEFAULT_REGION=<<AWS Region>> mount_s3 /bin/bash -c "./m
Fixed it , suggested env variables and included the variable name as run time. Good one!.

2023-03-23 16:28 UTC, mheshwg commented
Incorporated the review comments provided. please let me know if any more comments.

2023-03-28 16:37 UTC, dannycjones requested changes
Just a small note to enable use of short-term credentials. Looking to get this merged tomorrow if ready.

2023-03-28 16:45 UTC, mheshwg commented on README.md
> +        mount-s3 /bin/bash -c "./mount-s3 <<Bucket name>> /mnt; ls -l /mnt"
Included the recommended changes. Kindly merge for others to access.

2023-03-29 09:33 UTC, dannycjones commented
DCO check in CI will specify which commits need the sign-off trailer added. You can use an interactive rebase to pause to edit each commit listed, you run `git commit --amend --signoff --no-edit` on each commit it pauses at and, when complete, force push over your fork's branch.

2023-03-29 09:34 UTC, dannycjones approved these changes
Approved, but needs DCO fix on commits.

2023-03-29 11:11 UTC, mheshwg commented
> Is the source branch correct? Looks like there are some code changes included.

are you referring to *.rs files under mountpoint-s3/src?. I am not sure how these files are in.. these files are not part of my changes.. how do we remove those in this pull request?.. Is the change align with the main branch of yours?

2023-03-29 12:13 UTC, dannycjones commented
I'd propose to move your changes to a new branch on your fork and drop any commits that shouldn't be there, like the last two currently (6e0057a, a417443).

2023-03-29 15:17 UTC, monthonk commented
Replaced by https://github.com/awslabs/mountpoint-s3/pull/185

2023-03-29 15:17 UTC, closed without merging