add read-only mount option
awslabs/mountpoint-s3 pull request #353
Opened 2023-07-04 17:50 UTC by jchorl

## Description of change

Add a flag to mount as read-only.

Mounts used to be read-only always, but https://github.com/awslabs/mountpoint-s3/commit/e7bad12eca37ee46f91e9ecccfd1cd2657815f4e#diff-dc57c703340f88ddb4eab99dd8d870135117972f0f323c0a57b22a3f803b99ffL439 changed that.

First, thanks for adding write support!

It is nice to have the option to mount read-only, as a safety mechanism.

## Does this change impact existing behavior?

It doesn't change any defaults. It adds a new option.

---

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license and I agree to the terms of the [Developer Certificate of Origin (DCO)](https://developercertificate.org/).

2023-07-05 09:36 UTC, passaro requested changes
Thank you. This is definitely a useful option.

It would be great if you could also add a test for it. The module `fuse_tests::fork_test` would probably be the best fit (look for example at `fn run_in_foreground()`).

2023-07-05 09:36 UTC, passaro commented on mountpoint-s3/src/main.rs
> +        help = "Mount the filesystem in read-only mode",
nit: for consistency
```suggestion
        help = "Mount file system in read-only mode",
```

2023-07-06 03:30 UTC, jchorl commented
> Thank you. This is definitely a useful option.
> 
> It would be great if you could also add a test for it. The module `fuse_tests::fork_test` would probably be the best fit (look for example at `fn run_in_foreground()`).

Apologies, I should have done this without prompt. It took me a bit to figure out testing - env vars etc. Not sure if this is documented anywhere. I know the project is alpha so completely understand if its not.

Some tests panic'd for me, e.g. `fuse_tests::perm_test::permission_config_test_negative_mock::no_permissions`. However, my `readonly` test seems to have passed.

I debated how best to go about this - using a library to parse `mount` output, trying to write a fail and seeing it fail, etc. This to me seemed like the cleanest way to ensure a mount flag was passed all the way through to the `mount` call. Let me know if you'd prefer a different approach.

2023-07-06 12:46 UTC, passaro requested changes
Thank you for adding the test. I think the approach is fine and consistent with other tests in the module.

Only a couple of clippy issues.

2023-07-06 13:20 UTC, jchorl commented on mountpoint-s3/tests/fuse_tests/fork_test.rs
> +    match get_mount_from_source_and_mountpoint(source, mount_point) {
Cool, TIL `make fmt` and `make clippy`. Thanks for setting up those helpers. Will know for future.

2023-07-06 14:28 UTC, passaro approved these changes
All good. Thanks again for the contribution.

2023-07-06 14:29 UTC, merged