Added the mount option of disable additional checksum to support write in Outposts
awslabs/mountpoint-s3 pull request #677
Opened 2023-12-14 03:43 UTC by sauraank

## Description of change
Added the mount option of Disabling additional checksums to support write in Outposts. This is draft PR, since we have not finalised our decision on the way to do it. But, whatever decision we take we will need to make similar changes in `upload.rs` module. 
Users of Outposts will have to pass `--disable-checksum` to support write, if we go this path.

Passed the mount option to S3FileSystemConfig and then to uploader. Using this config, set the trailing checksum as false  and bypassing the checksum verification for the case above.
Manually tested it works with write on Outposts. I will need to add tests.

Relevant issues: 
#516 

## Does this change impact existing behavior?
Yes, it disables additional checksums in case of writing on Outpost bucket (in this way, set by user). It also adds a new mount option.

---

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license and I agree to the terms of the [Developer Certificate of Origin (DCO)](https://developercertificate.org/).

2023-12-14 11:31 UTC, passaro requested changes
While we discuss whether this is the right approach, I've commented on a couple of implementation details.

2023-12-14 11:31 UTC, passaro commented on mountpoint-s3/src/upload.rs
> +    set_checksum: bool,
Use consistent name here

2023-12-14 11:31 UTC, passaro commented on mountpoint-s3/src/upload.rs
>              hasher: Hasher::new(),
The `trailing_checksums` flag should also affect hashing: if disabled, we don't need the `Hasher`, or at least we don't need to calculate the checksum in `write`.

2023-12-14 11:31 UTC, passaro commented on mountpoint-s3/src/upload.rs
> +            .review_and_complete(move |review| verify_checksums(review, size, checksum, self.set_checksum))
You could skip the review completely and just call `PutObjectRequest::complete()` here.

2023-12-14 11:31 UTC, passaro commented on mountpoint-s3/src/upload.rs
> +            .review_and_complete(move |review| verify_checksums(review, size, checksum, self.set_checksum))
Alternatively, you could still use a review to verify just the size. In either cases, you do not want to calculate the checksum if not using it.

2023-12-31 18:45 UTC, chrsmia commented
I believe this also will be required for support with s3-snow compatible storage on Snowball Edge.  So there's greater need than just for Outposts.
SHA checksums are not matching causing write activities to fail.

2024-04-18 02:20 UTC, jamesbornholt commented
Moved to #849.

2024-04-18 02:20 UTC, closed without merging