Introduced support for the AWS_ENDPOINT_URL environment variable
awslabs/mountpoint-s3 pull request #895
Opened 2024-05-31 13:13 UTC by arsh

## Description of change

We have introduced support for the `AWS_ENDPOINT_URL` environment variable. The endpoint determination now follows this order:
- Use the CLI parameter `endpoint-url` if provided.
- Use `AWS_ENDPOINT_URL` if provided.
- Fallback to existing behavior

Relevant issues: https://github.com/awslabs/mountpoint-s3/issues/890

## Does this change impact existing behavior?

Yes, this change can impact existing behavior. Specifically, when the `AWS_ENDPOINT_URL` environment variable is set and no endpoint parameter is provided via `--endpoint-url`, the system will now use the `AWS_ENDPOINT_URL`. This provides an additional method for specifying the endpoint, which could affect how endpoints are resolved in certain configurations.

---

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license and I agree to the terms of the [Developer Certificate of Origin (DCO)](https://developercertificate.org/).

2024-06-03 09:58 UTC, dannycjones requested changes
Nice!

I have one comment that we need to handle an additional error case on URI parsing. Others are just minor test updates such as indentation, which I'm not sure why `rust-fmt` didn't flag.

2024-06-04 13:10 UTC, dannycjones submitted a review, later dismissed
LGTM

Pushed a minor fix to changelog

2024-06-04 13:22 UTC, arsh commented
> LGTM
> 
> Pushed a minor fix to changelog

Thank you!

2024-06-05 08:25 UTC, dannycjones approved these changes
LGTM

2024-06-05 08:52 UTC, merged